config/routes.rb
HopeHawaiiData::Application.routes.draw do

  
  devise_for :users
  root :to => "interventions#summary"

  get "interventions/summary"

  resources :recruits do
    resources :recruitments
    resources :interventions
  end

  resources :recruitments do
    resources :interventions
  end

  resources :interventions do
    resources :hospital_visits
    resources :er_visits
  end

  

end

app/models/recruitment.rb
class Recruitment < ActiveRecord::Base
	belongs_to :recruit
	has_many :interventions
	has_many :hospital_visits, through: :interventions
	has_many :er_visits, through: :interventions
end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController
	before_filter :authenticate_user!
  before_filter :find_recruits, only: [:new, :create, :edit, :update, :show]
  before_filter :find_recruitment, only: [:show, :edit, :update]
  before_filter :form_options, only: [:new, :edit]
  
  def index
  	@recruitments = Recruitment.all
  end

  def new
    @recruitment = Recruitment.new
  end

  def create
    @recruitment = @recruit.recruitments.build(params.require(:recruitment).permit(:recruit_id, :review_date, :account_number, :admission_date, :past_er_visits, :past_hosp_visits, :reason_admitted, :age, :eject_frac, :serum_albumin, :group))
    
    if @recruitment.save
      redirect_to recruit_path(@recruit)
    else
      render action: new
    end
  end

  def show
    @intervention = Intervention.where(recruitment_id: @recruitment.id).first
  end

  def edit
  end

  def update
  	@recruitment.update_attributes(params.require(:recruitment).permit(:recruit_id, :review_date, :account_number, :admission_date, :past_er_visits, :past_hosp_visits, :reason_admitted, :age, :eject_frac, :serum_albumin, :group))
    redirect_to recruit_recruitment_path
  end

  private

  def find_recruits
    @recruit = Recruit.find(params[:recruit_id])
  end
  
  def find_recruitment
  	@recruitment = Recruitment.find(params[:id])
  end

  def form_options
  	@group_options = ["Hilo 30-Day", "Hilo 1-Year", "Honolulu 1-Year"]
  	@nurse_options = ["Crystal", "Berlyn", "Mary Ann", "Christine"]
  	@outcome_options = ["Currently enrolled", "Died", "Withdrew", "Completed"]
  end
end

app/helpers/recruitments_helper.rb
module RecruitmentsHelper
end

app/views/recruitments/edit.html.erb
<div id="container">
	
  <div class="nav">
    <p><%= link_to "Home", recruits_path %></p>
  </div>

  <div class="one">
		<h1>Edit recruitment for <%= @recruit.first_name %></h1>
  </div>

  <div class="two">
  	<%= form_for [@recruit, @recruitment] do |form| %>

      <p>
        <%= form.label :group, "Program:" %>
        <%= form.select(:group, options_for_select(@group_options)) %>
      </p>

      <p>
        <%= form.label :review_date, "Review date:" %>
        <%= form.date_field :review_date %>
      </p>

      <p>
        <%= form.label :account_number, "Account Number:" %>
        <%= form.text_field :account_number %>
      </p>  

      <p>
        <%= form.label :admission_date, "Admission date:" %>
        <%= form.date_field :admission_date %>
      </p>

      <h3><u>Predisposing risk factors</u></h3>

      <p>  
        <%= form.label :past_er_visits, "Number of ER visits (DEP ER) in the past 6 months:" %>
        <%= form.text_field :past_er_visits %>
      </p>  

      <p>  
        <%= form.label :past_hosp_visits, "Number of hospitalizations (DIS IN) visits in the past 365 days:" %>
        <%= form.text_field :past_hosp_visits %>
      </p>  

      <p>  
        <%= form.label :reason_admitted, "Reason admitted:" %>
        <%= form.text_area :reason_admitted %>
      </p>  

      <p>  
        <%= form.label :eject_frac, "Ejection fraction:" %>
        <%= form.text_field :eject_frac %>
      </p>  
      
      <p>  
        <%= form.label :serum_albumin, "Serum albumin:" %>
        <%= form.text_field :serum_albumin %>
      </p>  
      
      <p><%= form.submit "Update" %></p>

      <br>
      
    <% end %>
  </div>
</div>

app/views/recruitments/index.html.erb
<div id="container">
	<div class="nav">
		<ul class="nav">
			<li><%= link_to "Summary", 'interventions/summary', class: "nav" %></li>
			<li><%= link_to "Patient List", recruits_path, class: "nav" %></li>
			<li><%= link_to "Recruitments", recruitments_path, class: "nav-selected"  %></li>
		</ul>
	</div>

	<div class="one">
		<h1>Recruits</h1>
	</div>

	<div class="two">

		<h1>All Recruitments</h1>
		<% @recruitments.each do |recruitment|  %>
			<ul>
				<li><%= link_to recruitment.review_date, recruit_recruitment_path(recruitment.recruit_id, recruitment) %></li>
				<li><%= link_to Recruit.find(recruitment.recruit_id).first_name, recruit_recruitment_path(recruitment.recruit_id, recruitment) %></li>
			</ul>
		<% end %>
	</div>

</div>

app/views/recruitments/new.html.erb
<div id="container">

	<p><%= link_to "Home", recruits_path %></p>

  <div class="one">
		<h1>New recruitment for <%= @recruit.first_name %></h1>
  </div>

  <div class="two">

  	<%= form_for [@recruit, @recruitment] do |form| %>
      <p>
        <%= form.label :review_date, "Review date:" %>
        <%= form.date_field :review_date %>
      </p>

      <p>
        <%= form.label :account_number, "Account Number:" %>
        <%= form.text_field :account_number %>
      </p>  

      <p>
        <%= form.label :admission_date, "Admission date:" %>
        <%= form.date_field :admission_date %>
      </p>

      <p>  
        <%= form.label :past_er_visits, "Number of ER visits in the past 6 months:" %>
        <%= form.text_field :past_er_visits %>
      </p>  
      


      <p><%= form.submit "Submit" %></p>
    <% end %>

  </div>
</div>

app/views/recruitments/show.html.erb
<div id="container">
  <div class="nav">
    <ul class="nav">
      <li><%= link_to "Summary", 'summary', class: "nav-selected" %></li>
      <li><%= link_to "Patient List", recruits_path, class: "nav" %></li>
      <li><%= link_to "Recruitments", recruitments_path, class: "nav"  %></li>
    </ul>
  </div>

  <div class="one">
    <h1>Recruitment for <%= link_to @recruit.first_name, recruit_path(@recruitment.recruit_id) %></h1>
  </div>

  <div class="two">

    <br>

    <table class="recruitment">
      <tr>
        <td class="right">Group</td>
        <td><%= @recruitment.group %></td>
      </tr>

      <tr>
        <td class="right">Review Date</td>
        <td><%= @recruitment.review_date %></td>
      </tr>

      <tr>
        <td class="right">Account Number</td>
        <td><%= @recruitment.account_number %></td>
      </tr>

      <tr>
        <td class="right">Admission Date</td>
        <td><%= @recruitment.admission_date %></td>
      </tr>

      <tr>
        <td class="right">Number of ER Visits in the Past 6 Months</td>
        <td><%= @recruitment.past_er_visits %></td>
      </tr>

      <tr>
        <td class="right">Number of Hospital Visits in the Past 365 Days</td>
        <td><%= @recruitment.past_hosp_visits %></td>
      </tr>

      <tr>
        <td class="right">Reason Admitted</td>
        <td><%= @recruitment.reason_admitted %></td>
      </tr>

      <tr>
        <td class="right">Ejection Fraction</td>
        <td><%= @recruitment.eject_frac %></td>
      </tr>
      
      <tr>
        <td class="right">Serum Albumin at Time of Admission</td>
        <td><%= @recruitment.serum_albumin %></td>
      </tr>
    </table>

    <h5><%= link_to "Edit", edit_recruit_recruitment_path(@recruit, @recruitment), class: "edit" %></h5>
    
    <br>

    <% if @intervention %>
      <p>Intervention start date: <%= @intervention.intervention_start_date %></p>
    <% else %>
    	<p><%= link_to "+ Add to intervention", new_recruitment_intervention_path(@recruitment), class: "add" %></p>
    <% end %>
    <br>

    <p><%= link_to "<< Back to #{@recruit.first_name}'s Profile", recruit_path(@recruit) %></p>
  </div>
</div>