config/routes.rb
HopeHawaiiData::Application.routes.draw do

  
  devise_for :users
  root :to => "interventions#summary"

  get "interventions/summary"

  resources :recruits do
    resources :recruitments
    resources :interventions
  end

  resources :recruitments do
    resources :interventions
  end

  resources :interventions do
    resources :hospital_visits
    resources :er_visits
  end

  

end

app/models/intervention.rb
class Intervention < ActiveRecord::Base
	has_many :hospital_visits
  has_many :er_visits
  belongs_to :recruitment
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
	before_filter :authenticate_user!
  before_filter :find_recruitment, only: [:new, :create, :edit, :update]
  before_filter :find_intervention, only: [:show, :edit, :update]
  before_filter :form_options, only: [:new, :edit]
  
  def index
  	@interventions = Intervention.all
  end

  def summary
    @hilo_30_recruitments = Recruitment.where(group: "Hilo 30-Day")
    @interventions = Intervention.all
  end

  def new
    @intervention = Intervention.new
  end

  def create
    @intervention = @recruitment.interventions.build(params.require(:intervention).permit(:nurse, :intervention_start_date, :intervention_end_date, :outcome))
    
    if @intervention.save
      redirect_to recruitment_intervention_path(@recruitment, @intervention)
    else
      render action: new
    end
  end

  def show
    @recruitment = Recruitment.find(@intervention.recruitment_id)
    @recruit = Recruit.find(@recruitment.recruit_id)
    @hospital_visits = HospitalVisit.where(intervention_id: @intervention)
    @er_visits = ErVisit.where(intervention_id: @intervention)
  end

  def edit
  end

  def update
  	@intervention.update_attributes(params.require(:intervention).permit(:group, :nurse, :intervention_start_date, :intervention_end_date, :previous_hospitalizations, :outcome))
    redirect_to recruitment_intervention_path
  end

  private

  def find_recruitment
    @recruitment = Recruitment.find(params[:recruitment_id])
  end

  def find_intervention
    @intervention = Intervention.find(params[:id])
  end

  def form_options
  	@group_options = ["Hilo 30-Day", "Hilo 1-Year", "Honolulu 1-Year"]
  	@nurse_options = ["Crystal", "Berlyn", "Mary Ann", "Christine"]
  	@outcome_options = ["Currently enrolled", "Died", "Withdrew", "Completed"]
  end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
	def find_recruit_recruitment(recruitment_id)
		Recruitment.find(recruitment_id)
	end
end

app/views/interventions/edit.html.erb
<h1>Edit Intervention ID <%= @intervention.id %></h1>

<%= form_for [@recruitment, @intervention] do |form| %>
  <p>
    <%= form.label :nurse, "Assigned nurse:" %>
    <%= form.select(:nurse, options_for_select(@nurse_options)) %>
  </p>

  <p>  
    <%= form.label :intervention_start_date, "Intervention start date:" %>
    <%= form.date_field :intervention_start_date %>
  </p>  
  
  <p>
    <%= form.label :intervention_end_date, "Intervention end date:" %>
    <%= form.date_field :intervention_end_date %>
  </p>

  <p>
    <%= form.label :outcome, "Number of hospitalizations in the previous year:" %>
  	<%= form.select(:outcome, options_for_select(@outcome_options)) %>  
  </p>

  <p><%= form.submit "Update" %></p>

<% end %>

app/views/interventions/index.html.erb
<h1>All Interventions</h1>

<% @interventions.each do |intervention| %>
	<ul>
		<li><%= %></li>
	</ul>
<% end %>

app/views/interventions/new.html.erb
<h1>Interventions</h1>
<br>

<%= form_for [@recruitment, @intervention] do |form| %>
  <p>
    <%= form.label :nurse, "Assigned nurse:" %>
    <%= form.select(:nurse, options_for_select(@nurse_options), {:prompt => "Select assigned nurse"}) %>
  </p>

  <p>  
    <%= form.label :intervention_start_date, "Intervention start date:" %>
    <%= form.date_field :intervention_start_date %>
  </p>  
  
  <p>
    <%= form.label :intervention_end_date, "Intervention end date:" %>
    <%= form.date_field :intervention_end_date %>
  </p>

   <p>
    <%= form.label :outcome, "Intervention outcome:" %>
   	<%= form.select(:outcome, options_for_select(@outcome_options), {:prompt => "Select outcome"}) %>  </p>

  <p><%= form.submit "Submit" %></p>

<% end %>

app/views/interventions/show.html.erb
<div id="container">
	<div class="nav">
		<ul class="nav">
			<li><%= link_to "Summary", '/interventions/summary', class: "nav" %></li>
			<li><%= link_to "Patient List", recruits_path, class: "nav" %></li>
			<li><%= link_to "Recruitments", recruitments_path, class: "nav"  %></li>
		</ul>
	</div>

	<div class="one">
		<h3><%= "Intervention ID: #{@intervention.id}" %></h3>

		<h2>Participant: <%= link_to "#{@recruit.last_name}, #{@recruit.first_name} #{@recruit.middle_initial}", recruit_path(@recruit.id) %></h2>

		<h3>MRN: <%= link_to "#{@recruit.medical_record_number}", recruit_path(@recruit) %></h3>
		<h4>Program: <%= @recruitment.group %></h4>
		<h4>Nurse: <%= @intervention.nurse %></h4>
	</div>

	<div class="two">
		<h4>Intervention Start Date: <%= @intervention.intervention_start_date %></h4>
		<h4>Intervention End Date: <%= @intervention.intervention_end_date %></h4>
		<p><%= link_to "Update", edit_recruitment_intervention_path(@recruitment, @intervention), class: "edit" %></p>
	</div>
	
	<br>

	<div class="table">
		<table>
			<tr>
				<th colspan="7">Hospital Visits</th>
			</tr>
			
			<tr>
				<th class="hosp">#</th>
				<th class="hosp">Admission Date</th>
				<th class="hosp">Discharge Date</th>
				<th class="hosp">ICD 9 Code</th>
				<th class="hosp">ICD 9 Detail</th>
				<th class="hosp">Cost</th>
				<th class="hosp">Edit</th>
			</tr>

			<% count = 1 %>

			<% @hospital_visits.order("admission_date").each do |hospital_visit| %>
				<tr>
					<td><%= link_to "H#{count}", intervention_hospital_visit_path(@intervention, hospital_visit) %></td>
					
					<% count += 1 %>
					
					<td><%= link_to hospital_visit[:admission_date], intervention_hospital_visit_path(@intervention, hospital_visit) %></td>
					<td><%= hospital_visit[:discharge_date] %></td>
					<td><%= hospital_visit[:icd9_code] %></td>
					<td><%= hospital_visit[:icd9_detail] %></td>
					<td><%= hospital_visit[:cost] %></td>
					<td><%= link_to "Update", edit_intervention_hospital_visit_path(@intervention, hospital_visit) %></td>
				</tr>
			<% end %>
		</table>

		<p><%= link_to "+ Add hospital visit", new_intervention_hospital_visit_path(@intervention) %></p>

		<br>

		<table>
			<tr>
				<th colspan="7">ER Visits</th>
			</tr>
			
			<tr>
				<th class="er">#</th>
				<th class="er">ER Visit Date</th>
				<th class="er">ICD 9 Code</th>
				<th class="er">ICD 9 Detail</th>
				<th class="er">Cost</th>
				<th class="er">Notes</th>
				<th class="er">Edit</th>
			</tr>

		<% count = 1 %>
		<% @er_visits.order("er_date").each do |er_visit| %>
			<tr>
				<td><%= "ER#{count}" %></td>

				<% count += 1 %>

				<td><%= link_to er_visit[:er_date], intervention_er_visit_path(@intervention, er_visit) %></td>
				<td><%= er_visit[:er_icd9_code] %></td>
				<td><%= er_visit[:er_icd9_detail] %></td>
				<td><%= er_visit[:er_cost] %></td>
				<td><%= er_visit[:er_notes] %></td>
				<td><%= link_to "Update", edit_intervention_er_visit_path(@intervention, er_visit) %></td>
			</tr>
		<% end %>
		</table>

		<p><%= link_to "+ Add emergency room (ER) visit", new_intervention_er_visit_path(@intervention) %></p>
	</div>
	
	<br>
	<br>

	<h5><%= link_to "<< Back to #{@recruit.first_name}'s profile", recruit_path(@recruitment.recruit_id) %></h5>
</div>

app/views/interventions/summary.html.erb
<div id="container">
	<div class="nav">
		<ul class="nav">
			<li><%= link_to "Summary", 'summary', class: "nav-selected" %></li>
			<li><%= link_to "Patient List", recruits_path, class: "nav" %></li>
			<li><%= link_to "Recruitments", recruitments_path, class: "nav"  %></li>
		</ul>
	</div>

	<div class="one">
		<h1>Change</h1>
	</div>

	<div class="two">
		<h3>Hilo 30-Day Intervention Summary</h3>
			<% @interventions.each do |intervention| %>
				<% if Recruitment.find(intervention.recruitment_id).group = "Hilo 30-Day" %>
						<ul>
							<li><%= intervention.outcome %></li>
						</ul>
				<% end %>
			<% end %>



		<h3>Hilo 1-Year Intervention Summary</h3>



		<h3>Honolulu 1-Year Intervention Summary</h3>
	</div>
</div>