config/routes.rb
HopeHawaiiData::Application.routes.draw do

  
  devise_for :users
  root :to => "interventions#summary"

  get "interventions/summary"

  resources :recruits do
    resources :recruitments
    resources :interventions
  end

  resources :recruitments do
    resources :interventions
  end

  resources :interventions do
    resources :hospital_visits
    resources :er_visits
  end

  

end

app/models/recruit.rb
class Recruit < ActiveRecord::Base
	has_many :recruitments
	has_many :interventions, through: :recruitments
	has_many :hospital_visits, through: :interventions
	has_many :er_visits, through: :interventions

  # validates :medical_record_number, length: {is: 12}
  	

end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  before_filter :authenticate_user!, :find_recruit, only: [:show, :edit, :update] #Requires that a User is signed in to view any Participant page.

  before_filter :sex_options, only: [:new, :edit]

  def new
  	@recruit = Recruit.new
  end

  def create
  	@recruit = Recruit.new(params.require(:recruit).permit(:first_name, :last_name, :medical_record_number, :date_of_birth, :middle_initial, :sex))

  	if @recruit.save
  		redirect_to @recruit
  	else
  		render action: new
  	end
  end

  def index
  	@recruits = Recruit.all
  end

  def show
    @recruitments = Recruitment.where(recruit_id: @recruit.id)
    @interventions = Intervention.all
    @current_date = Date.today
    @hospital_visits = HospitalVisit.all
    @er_visits = ErVisit.all
	end

  def edit
  end

  def update
  	@recruit.update_attributes(params.require(:recruit).permit(:first_name, :last_name, :medical_record_number, :date_of_birth, :middle_initial, :sex))
  	redirect_to @recruit
  end

  private

  def find_recruit
  	@recruit = Recruit.find(params[:id])
  end

  def recruit_params
  end

  def sex_options
    @sex_options = ["Male", "Female"]
  end
end

app/helpers/recruits_helper.rb
module RecruitsHelper
	def current_age(date_of_birth)
		if @current_date.month <= date_of_birth.try(:month) && @current_date.day < date_of_birth.day
			@current_age = @current_date.year - date_of_birth.year - 1
		else
			@current_age = @current_date.year - date_of_birth.year
		end
	end
end

app/views/recruits/edit.html.erb
<div id="container">
  
  <div class="nav">
    <p><%= link_to "Home", recruits_path %></p>
  </div>

  <div class="one">
    <h1>Edit Profile</h1>
  </div>
  
  <div class="two">

    <%= form_for @recruit do |form| %>
      <p>
        <%= form.label :first_name, "First name:" %>
        <%= form.text_field :first_name %>
      </p>

      <p>
        <%= form.label :middle_initial, "Middle initial(s):" %>
        <%= form.text_field :middle_initial %>
      </p> 
      
      <p>
        <%= form.label :last_name, "Last name:" %>
        <%= form.text_field :last_name %>
      </p>

      <p>  
        <%= form.label :medical_record_number, "MRN:" %>
        <%= form.text_field :medical_record_number %>
      </p>  
      
      <p>
        <%= form.label :date_of_birth, "Date of birth:" %>
        <%= form.date_field :date_of_birth %>
      </p>

      <p>
        <%= form.label :sex, "Sex:" %>
        <%= form.select(:sex, options_for_select(@sex_options)) %>
      </p>

      <p><%= form.submit "Update" %></p>
    <% end %>
  </div>
</div>

app/views/recruits/index.html.erb
<div id="container">
	<div class="nav">
		<ul class="nav">
			<li><%= link_to "Summary", 'interventions/summary', class: "nav" %></li>
			<li><%= link_to "Patient List", recruits_path, class: "nav-selected" %></li>
			<li><%= link_to "Recruitments", recruitments_path, class: "nav"  %></li>
		</ul>
	</div>

	<div class="one">
		<h1>Recruits</h1>
	</div>

	<div class="two">
		
		<br>
		
		<p><%= link_to "+ Add new recruit", new_recruit_path, class: "add" %></p>
		
		<br>
		
		<table>
			<tr>
				<th>Last Name</th>
				<th>First Name</th>
				<th>Middle Initial</th>
				<th>Sex</th>
				<th>Date of Birth</th>
				<th>Medical Record Number</th>
			</tr>

			<% @recruits.order("last_name").each do |recruit| %>
				<tr>
					<td class="string"><%= link_to recruit.last_name, recruit_path(recruit.id) %></td>
					<td class="string"><%= link_to recruit.first_name, recruit_path(recruit.id) %></td>					
					<td class="string"><%= link_to recruit.middle_initial, recruit_path(recruit.id) %></td>					
					<td class="string"><%= recruit.sex %></td>
					<td><%= link_to "#{recruit.date_of_birth}", recruit_path(recruit.id) %></td>
					<td><%= link_to "#{recruit.medical_record_number}", recruit_path(recruit.id) %></td>
				</tr>
			<% end %>
		</table>

		<br>
		<br>

	</div>
</div>

app/views/recruits/new.html.erb
<div id="container" class="form">
  <div class="nav">
    <h5><%= link_to "Home", recruits_path, class: "nav" %></h5>
  </div>
  
  <div class="one">
    <h1>New Recruit Form</h1>
  </div>

  <div class="two">
    <%= form_for @recruit do |form| %>
      <%#= form.error_messages_for :medical_record_number %>
      <p>
        <%= form.label :first_name, "First name:" %>
        <%= form.text_field :first_name %>
      </p>

      <p>
        <%= form.label :middle_initial, "Middle initial(s):" %>
        <%= form.text_field :middle_initial %>
      </p>  

      <p>
        <%= form.label :last_name, "Last name:" %>
        <%= form.text_field :last_name %>
      </p>

      <p>  
        <%= form.label :medical_record_number, "Medical Record Number:" %>
        <%= form.text_field :medical_record_number %>
      </p>  
      
      <p>
        <%= form.label :date_of_birth, "Date of birth:" %>
        <%= form.date_field :date_of_birth %>
      </p>

      <p>
        <%= form.label :sex, "Sex:" %>
        <%= form.select(:sex, options_for_select(@sex_options), {:prompt => "Select sex"}) %>
      </p>

      <p><%= form.submit "Submit" %></p>
    <% end %>
  </div>
</div>

app/views/recruits/show.html.erb
<div id="container">
	<div class="nav">
		<ul class="nav">
			<li><%= link_to "Summary", '/interventions/summary', class: "nav" %></li>
			<li><%= link_to "Patient List", recruits_path, class: "nav" %></li>
			<li><%= link_to "Recruitments", recruitments_path, class: "nav"  %></li>
		</ul>
	</div>

	<div class="one">
		<h1>Patient Profile</h1>
	</div>

	<div class="two">
		<h2><u>Name</u>: <%= "#{@recruit.last_name}, #{@recruit.first_name} #{@recruit.middle_initial}" %></h2>

		<h3><u>Date of birth</u>: <%= @recruit.date_of_birth.try(:strftime, "%B %-d, %Y") %></h3>		

		<h3><u>Sex</u>: <%= @recruit.sex %></h3>

		<h3 class="underline">Age at time of recruitment</h3>

		<h3><u><%= "Medical Record Number"%></u><%= ": #{@recruit.medical_record_number}" %></h3>

		<p><%= link_to "Edit profile", edit_recruit_path %></p>

	</div>

	<div class="table">
		<h2>Recruitments</h2>
		<% if @recruitments.count > 0%>
			<table>
				<tr>
					<th>Number</th>
					<th>Date</th>
					<th>Account Number</th>
				</tr>
				<% count = 1 %>
				<% @recruitments.each do |recruitment| %>
					<tr>
						<td><%= link_to count, recruit_recruitment_path(@recruit, recruitment.id) %></td>
						<td><%= link_to recruitment.admission_date, recruit_recruitment_path(@recruit, recruitment.id) %></td>
						<td><%= link_to recruitment.account_number, recruit_recruitment_path(@recruit, recruitment.id) %></td>
					</tr>
					<% count += 1%>
				<% end %>
			</table>
		<% end %>

		<br>
		
		<h3><%= link_to "+ Add recruitment", new_recruit_recruitment_path(params[:id]), class: "add" %></h3>

		<br>
		<br>

		<% if @recruit.interventions.count > 0 %>
			<h2>Interventions</h2>
			<table>
				<tr>
					<th class="column1">Intervention ID</th>
					<th>Intervention Group</th>
					<th>Nurse</th>
					<th>Start Date</th>
					<th>End Date</th>
					<th>Hospitalizations</th>
					<th>ER Visits</th>
					<th>Outcome</th>
					<th>Update</th>
				</tr>

				<% @recruit.interventions.each do |intervention| %>
					<tr>
						<td><%= link_to intervention.id, recruitment_intervention_path(intervention.recruitment_id, intervention.id) %></td>
						<td><%= find_recruit_recruitment(intervention.recruitment_id).group %></td>
						<td><%= intervention.nurse %></td>
						<td><%= intervention.intervention_start_date %></td>
						<td><%= intervention.intervention_end_date %></td>
						<td><%= link_to @hospital_visits.where(intervention_id: intervention.id).count, recruit_intervention_path(params[:id], intervention.id) %></td>
						<td><%= link_to @er_visits.where(intervention_id: intervention.id).count, recruit_intervention_path(params[:id], intervention.id) %></td>
						<td><%= intervention.outcome %></td>
						<td><%= link_to "Update", edit_recruitment_intervention_path(intervention.recruitment_id, intervention.id) %></td>
					</tr>
				<% end %>
			</table>
		<% else %>

		<% end %>

		<br>

		<p><%= link_to "<< Back to all recruits", recruits_path %></p>
	</div>
</div>